# Generated by Django 2.1.4 on 2018-12-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookimage',
            options={'verbose_name': 'Фотография книги', 'verbose_name_plural': 'Фотографии книг'},
        ),
    ]
