# Generated by Django 2.1.4 on 2019-01-01 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_shot_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='shot_description',
            new_name='short_description',
        ),
    ]
