# Generated by Django 2.1.4 on 2019-01-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20190101_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
