# Generated by Django 2.1.4 on 2019-01-04 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_bookimage_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Категории товаров',
                'verbose_name': 'Категория товара',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.BookCategory'),
        ),
    ]
