# Generated by Django 2.1.4 on 2019-01-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20190104_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcategory',
            options={'verbose_name': 'Категория книги', 'verbose_name_plural': 'Категория книг'},
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
