# Generated by Django 2.1.4 on 2019-02-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20190209_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='bookcategory',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
