# Generated by Django 2.1.4 on 2019-02-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_visual'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visual',
        ),
        migrations.AddField(
            model_name='bookimage',
            name='is_slider',
            field=models.BooleanField(default=False),
        ),
    ]
