# Generated by Django 2.1.4 on 2019-01-20 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20190104_1622'),
        ('orders', '0004_auto_20181227_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('price_per_item', models.DecimalField(decimal_places=2, default=None, max_digits=7)),
                ('total_price', models.DecimalField(decimal_places=2, default=None, max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('book', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
            options={
                'verbose_name': 'Книга в корзине',
                'verbose_name_plural': 'Книги  в корзине',
            },
        ),
    ]
