# Generated by Django 2.1.4 on 2019-02-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190201_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='user',
        ),
    ]
