# Generated by Django 2.1.4 on 2019-02-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190205_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinbasket',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
